function mixWithWhite(hex, amount) {
    const value = parseInt(hex.slice(1), 16);
    const channels = [(value >> 16) & 255, (value >> 8) & 255, value & 255];
    const mixed = channels.map((channel) => Math.round(channel + (255 - channel) * amount));
    return `#${mixed.map((channel) => channel.toString(16).padStart(2, '0')).join('')}`;
}

export function createOrbGradient(hex) {
    return `radial-gradient(circle at 48% 50%, ${hex} 0%, ${mixWithWhite(hex, 0.28)} 30%, ${mixWithWhite(hex, 0.58)} 65%, ${mixWithWhite(hex, 0.85)} 100%)`;
}

export const EXTENDED_ORB_PALETTE = [
    { key: 'colorLightBlue', hex: '#CBD9EA' },
    { key: 'colorDeeperBlue', hex: '#C5D3E4' },
    { key: 'colorVividMagenta', hex: '#C85078' },
    { key: 'colorMediumPink', hex: '#C88CB4' },
    { key: 'colorLightPink', hex: '#C8B4C8' },
    { key: 'colorCyanTeal', hex: '#78BEBE' },
    { key: 'colorTealGreen', hex: '#78C8BE' },
    { key: 'colorRoseMagenta', hex: '#E68CA0' },
    { key: 'colorBrightRose', hex: '#F08CAA' },
    { key: 'colorRosePink', hex: '#F096B4' },
    { key: 'colorSoftPeach', hex: '#F0BE96' },
    { key: 'colorWarmTan', hex: '#F0C896' },
    { key: 'colorBrightBlue', hex: '#96BEFA' },
    { key: 'colorDeepBrightBlue', hex: '#8CB4FA' },
    { key: 'colorSunYellow', hex: '#F0E060' },
    { key: 'colorSoftLavender', hex: '#C0A0E6' },
    { key: 'colorLightGreen', hex: '#A8D8A0' },
    { key: 'colorLoveMagenta', hex: '#DC508C' },
    { key: 'colorDeepMagenta', hex: '#DC3C78' },
    { key: 'colorBrightPink', hex: '#E65A8C' },
    { key: 'colorBlush', hex: '#E49CA8' },
    { key: 'colorSoftRose', hex: '#E4A8A8' },
    { key: 'colorWarmOrange', hex: '#C88C5A' },
    { key: 'colorTan', hex: '#D2965A' },
    { key: 'colorPalePeach', hex: '#F0CC9C' },
    { key: 'colorSageGreen', hex: '#B0C0A0' },
    { key: 'colorPaleYellow', hex: '#F0D060' },
    { key: 'colorPastelLavender', hex: '#E6E6F0' },
    { key: 'colorPaleViolet', hex: '#DCDCF0' },
    { key: 'colorPalePink', hex: '#F0E6E6' },
    { key: 'colorPastelBlush', hex: '#F0DCE6' },
    { key: 'colorDustyPink', hex: '#F0DCDC' },
    { key: 'colorPastelBlue', hex: '#DCE6F0' },
    { key: 'colorPaleYellowGreen', hex: '#F0F0E6' },
    { key: 'colorMutedYellowGreen', hex: '#E6E6DC' },
    { key: 'colorPastelPeach', hex: '#F0E6DC' },
    { key: 'colorSoftOrange', hex: '#F0DCD2' },
    { key: 'colorViolet', hex: '#9888D8' },
    { key: 'colorDeepViolet', hex: '#8878C8' },
];

/** Display order for the picker grid — 9×6, grouped by hue (stored colorIndex unchanged). */
export const SWATCH_DISPLAY_ORDER = [
    // Teals & greens
    0, 1, 20, 21, 31, 40, 48, 49, 14,
    // Blues → periwinkle → pale violet
    2, 15, 16, 27, 28, 47, 3, 42, 43,
    // Lavender & violet → mauve → pink
    4, 30, 52, 53, 19, 18, 5, 6, 7,
    // Magenta & rose
    8, 17, 32, 33, 34, 22, 23, 24, 35,
    // Soft rose, blush & peach
    36, 44, 45, 46, 9, 25, 39, 50, 51,
    // Orange, coral, tan & yellow
    10, 11, 12, 37, 26, 38, 29, 13, 41,
];

export function migrateLegacyColorIndex(index) {
    if (index === 1 || index === 2) return 0;
    if (index > 2) return index - 2;
    return index;
}

export function getSwatchDisplayOrder(totalColors) {
    return SWATCH_DISPLAY_ORDER.filter((index) => index < totalColors);
}

export const EXTENDED_COLOR_LABELS = {
    en: {
        colorLightBlue: 'Light Blue',
        colorDeeperBlue: 'Deeper Blue',
        colorVividMagenta: 'Vivid Magenta',
        colorMediumPink: 'Medium Pink',
        colorLightPink: 'Light Pink',
        colorCyanTeal: 'Cyan Teal',
        colorTealGreen: 'Teal Green',
        colorRoseMagenta: 'Rose Magenta',
        colorBrightRose: 'Bright Rose',
        colorRosePink: 'Rose Pink',
        colorSoftPeach: 'Soft Peach',
        colorWarmTan: 'Warm Tan',
        colorBrightBlue: 'Bright Blue',
        colorDeepBrightBlue: 'Deep Bright Blue',
        colorSunYellow: 'Sun Yellow',
        colorSoftLavender: 'Soft Lavender',
        colorLightGreen: 'Light Green',
        colorLoveMagenta: 'Love Magenta',
        colorDeepMagenta: 'Deep Magenta',
        colorBrightPink: 'Bright Pink',
        colorBlush: 'Blush',
        colorSoftRose: 'Soft Rose',
        colorWarmOrange: 'Warm Orange',
        colorTan: 'Tan',
        colorPalePeach: 'Pale Peach',
        colorSageGreen: 'Sage Green',
        colorPaleYellow: 'Pale Yellow',
        colorPastelLavender: 'Pastel Lavender',
        colorPaleViolet: 'Pale Violet',
        colorPalePink: 'Pale Pink',
        colorPastelBlush: 'Pastel Blush',
        colorDustyPink: 'Dusty Pink',
        colorPastelBlue: 'Pastel Blue',
        colorPaleYellowGreen: 'Pale Yellow Green',
        colorMutedYellowGreen: 'Muted Yellow Green',
        colorPastelPeach: 'Pastel Peach',
        colorSoftOrange: 'Soft Orange',
        colorViolet: 'Violet',
        colorDeepViolet: 'Deep Violet',
    },
    es: {
        colorLightBlue: 'Azul claro',
        colorDeeperBlue: 'Azul profundo',
        colorVividMagenta: 'Magenta vivo',
        colorMediumPink: 'Rosa medio',
        colorLightPink: 'Rosa claro',
        colorCyanTeal: 'Cian verde azulado',
        colorTealGreen: 'Verde azulado',
        colorRoseMagenta: 'Magenta rosado',
        colorBrightRose: 'Rosa brillante',
        colorRosePink: 'Rosa rosado',
        colorSoftPeach: 'Melocotón suave',
        colorWarmTan: 'Bronce cálido',
        colorBrightBlue: 'Azul brillante',
        colorDeepBrightBlue: 'Azul intenso',
        colorSunYellow: 'Amarillo sol',
        colorSoftLavender: 'Lavanda suave',
        colorLightGreen: 'Verde claro',
        colorLoveMagenta: 'Magenta amor',
        colorDeepMagenta: 'Magenta profundo',
        colorBrightPink: 'Rosa vivo',
        colorBlush: 'Rubor',
        colorSoftRose: 'Rosa suave',
        colorWarmOrange: 'Naranja cálido',
        colorTan: 'Bronceado',
        colorPalePeach: 'Melocotón pálido',
        colorSageGreen: 'Verde salvia',
        colorPaleYellow: 'Amarillo pálido',
        colorPastelLavender: 'Lavanda pastel',
        colorPaleViolet: 'Violeta pálido',
        colorPalePink: 'Rosa pálido',
        colorPastelBlush: 'Rubor pastel',
        colorDustyPink: 'Rosa empolvado',
        colorPastelBlue: 'Azul pastel',
        colorPaleYellowGreen: 'Verde amarillo pálido',
        colorMutedYellowGreen: 'Verde amarillo apagado',
        colorPastelPeach: 'Melocotón pastel',
        colorSoftOrange: 'Naranja suave',
        colorViolet: 'Violeta',
        colorDeepViolet: 'Violeta profundo',
    },
    it: {
        colorLightBlue: 'Azzurro chiaro',
        colorDeeperBlue: 'Blu profondo',
        colorVividMagenta: 'Magenta vivo',
        colorMediumPink: 'Rosa medio',
        colorLightPink: 'Rosa chiaro',
        colorCyanTeal: 'Ciano teal',
        colorTealGreen: 'Verde teal',
        colorRoseMagenta: 'Magenta rosato',
        colorBrightRose: 'Rosa brillante',
        colorRosePink: 'Rosa rosato',
        colorSoftPeach: 'Pesca morbida',
        colorWarmTan: 'Marrone caldo',
        colorBrightBlue: 'Blu brillante',
        colorDeepBrightBlue: 'Blu intenso',
        colorSunYellow: 'Giallo sole',
        colorSoftLavender: 'Lavanda morbida',
        colorLightGreen: 'Verde chiaro',
        colorLoveMagenta: 'Magenta amore',
        colorDeepMagenta: 'Magenta profondo',
        colorBrightPink: 'Rosa vivo',
        colorBlush: 'Rosato',
        colorSoftRose: 'Rosa tenue',
        colorWarmOrange: 'Arancione caldo',
        colorTan: 'Marrone chiaro',
        colorPalePeach: 'Pesca pallida',
        colorSageGreen: 'Verde salvia',
        colorPaleYellow: 'Giallo pallido',
        colorPastelLavender: 'Lavanda pastello',
        colorPaleViolet: 'Viola pallido',
        colorPalePink: 'Rosa pallido',
        colorPastelBlush: 'Rosato pastello',
        colorDustyPink: 'Rosa polveroso',
        colorPastelBlue: 'Blu pastello',
        colorPaleYellowGreen: 'Verde giallo pallido',
        colorMutedYellowGreen: 'Verde giallo tenue',
        colorPastelPeach: 'Pesca pastello',
        colorSoftOrange: 'Arancione morbido',
        colorViolet: 'Viola',
        colorDeepViolet: 'Viola intenso',
    },
};
